----   CRIAÇÃO DE TABELAS NA PRATICA   ----

---  EXEMPLO 01 DE CRIAÇÃO DE TABELA  ---

CREATE TABLE Canal (
CanalId INT PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
ContagemInscritos INT DEFAULT 0,
DataCriacao DATETIME NOT NULL
)

--- TESTE PARA VER SE FOI CRIADA  ---
SELECT *
FROM Canal



---  EXEMPLO 02 DE CRIAÇÃO DE TABELA  ---

CREATE TABLE Video (
VideoId INT PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
Visualizacoes INT DEFAULT 0,
Likes INT DEFAULT 0,
Dislikes INT DEFAULT 0,
Duracao INT NOT NULL,
CanalId INT FOREIGN KEY REFERENCES Canal(CanalId)
);


--- TESTE PARA VER SE FOI CRIADA  ---
SELECT *
FROM Video


--- TESTE JUNTAR TABELAS  ---
SELECT *
FROM Canal AS C
INNER JOIN Video AS V 
ON c.CanalId = v.CanalId