----    CRIAÇÃO DE TABELAS    ----

  --- PRINCIPAIS TIPOS DE RESTRIÇÃO QUE PODEM SER APLICADAS ---
   -- NOT NULL (NÃO PERMITE NULOS) --
   -- UNIQUE (FORÇA TODOS OS VALORES EM UMA COLUNA A SEREM DIRERENTES)
   -- PRIMARY KEY (UMA JUNÇÃO DE NOT NULL E UNIQUE)
   -- FOREIGN KEY (IDENTIFICA UNICAMENTE UMA LINHA EM OUTRA TABELA)
   -- CHECK (FORÇA UMA CONDIÇÃO ESPECIFICA EM UMA COLUNA)
   -- DEFAULT(FORÇA UM VALOR PADRÃO QUANDO NENHUM VALOR E PASSADO) 

  --- CRIANDO UMA TABELA DO ZERO ---
    -- SINTAXE --
	--CREATE TABLE NomeTabela(
	--    coluna1 tipo RestriçãoDaTabela,
	--	coluna2 tipo RestriçãoDaTabela,
	--	coluna3 tipo RestriçãoDaTabela,
	--	....
	--)



