--- DESAFIO 03 ---
--- USANDO COUNT ( DISTINCT )
--- EM QUANTAS CIDADES ÚNICAS ESTÃO CADASTRADOS NOSSOS CLIENTES? ---

SELECT COUNT (DISTINCT City)
FROM Person.Address



--- OU USAR O SEGUINTE COMANDO ---

SELECT DISTINCT City
FROM Person.Address
