--- DESAFIO 01 HAVING ---
--- ESTAMOS QUERENDO IDENTIFICAR AS PROVINCIAS (StateProvinceId) COM MAIOR NUMERO DE CADASTROS EM NOSSO SISTEMA --
 -- ENTÃO É PRECISO ENCONTRAR QUAIS PROVINCIAS (StateProvinceId) ESTÃO REGISTRADAS NO BANCO DE DADOS MAIS QUE 1000 VEZES ---

 SELECT StateProvinceID, COUNT(StateProvinceID) AS "CADASTROS ACIMA DE 1000"
 FROM Person.Address
 GROUP BY StateProvinceID
 HAVING COUNT(StateProvinceID) > 1000
 ORDER BY COUNT(StateProvinceID) DESC


 --- DESAFIO 02 HAVING ---
--- SENDO QUE SE TRATA DE UMA MULTINAIONAL, OS GERENTES ESTÃO QUERENDO SABER  QUAIS PRODUTOS (ProductId) NÃO ESTÃO TRAZENDO --
 -- EM MEDIA NO MINIMO 1 MILHÃO EM TOTAL DE VENDAS (LineTotal) ---

 SELECT ProductID, AVG(LineTotal) AS "PRODUTOS COM MEDIA ABAIXO DE 1 MILHÃO"
 FROM Sales.SalesOrderDetail
 GROUP BY ProductID
 HAVING AVG(LineTotal) < 1000000
 ORDER BY AVG(LineTotal) ASC