--- DESAFIO 01 ---
--- QUANTAS PESSOAS TEM O MESMO MiddleName AGRUPADAS POR UM MiddleName? ---

SELECT MiddleName, COUNT(MiddleName) AS "QUANTIDADE DE PESSOAS COM MESMO APELIDO"
FROM Person.Person
GROUP BY MiddleName