--- DESAFIO 02 ---
--- EM MÉDIA QUAL QUANTIDADE (Quantity) QUE CADA PRODUTO E VENDIDO NA LOJA? ---

SELECT ProductID, AVG(OrderQty) AS " MEDIA VENDA CADA PRODUTO"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY ProductID ASC
