--- DESAFIO 03---
--- QUAIS FORAM AS 10 VENDAS, QUE NO TOTAL, TIVERAM OS MAIORES VALORES  DE VENDA (Line Total) POR PRODUTO, SENDO DO MAIOR PARA O MENOR ---

SELECT TOP 10 ProductID, SUM(LineTotal) AS "LISTA DE PRODUTOS DO MAIOR VALOR VENDIDO AO MENOR VALOR VENDIDO"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) DESC