--- DESAFIO 02 ---
--- USANDO COMANDO LIKE ---
--- QUANTAS PESSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P? ---

SELECT COUNT(FirstName) 
FROM Person.Person
WHERE FirstName LIKE 'P%'

--- OU POSSO FAZER DA SEGUINTE FORMA ---

SELECT FirstName
FROM Person.Person
WHERE FirstName LIKE 'P%'