/****** FOI PEDIDO PELO MARKETING UMA RELAÇÃO DE TODOS OS EMPREGADOS (EMPLOYEERS) QUE SÃO CASADOS
(SINGLE=SOLTEIRO , MARRIED=CASADO)E SÃO ASSALARIADOS (SALARIED)  ******/

SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'M' and SalariedFlag = 1